---

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data/
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    develop:
      watch:
        - action: rebuild
          path: cmd/app/
        - action: rebuild
          path: internal/
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
        - action: rebuild
          path: Dockerfile
